//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Categories {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Categories() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Localization.Categories", typeof(Categories).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Искусство.
        /// </summary>
        public static string RootArt {
            get {
                return ResourceManager.GetString("RootArt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Одежда и Мода.
        /// </summary>
        public static string RootClothesFashion {
            get {
                return ResourceManager.GetString("RootClothesFashion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Облачные Вычисления.
        /// </summary>
        public static string RootCloudComputing {
            get {
                return ResourceManager.GetString("RootCloudComputing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Компьютеры и комплектующие.
        /// </summary>
        public static string RootComputerAccessories {
            get {
                return ResourceManager.GetString("RootComputerAccessories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мастера.
        /// </summary>
        public static string RootCraftsman {
            get {
                return ResourceManager.GetString("RootCraftsman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Электроника.
        /// </summary>
        public static string RootElectronics {
            get {
                return ResourceManager.GetString("RootElectronics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Развлечения.
        /// </summary>
        public static string RootEntertainment {
            get {
                return ResourceManager.GetString("RootEntertainment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Эротика.
        /// </summary>
        public static string RootErotic {
            get {
                return ResourceManager.GetString("RootErotic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Еда и Напитки.
        /// </summary>
        public static string RootFoodBeverage {
            get {
                return ResourceManager.GetString("RootFoodBeverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для Компаний.
        /// </summary>
        public static string RootForCompanies {
            get {
                return ResourceManager.GetString("RootForCompanies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Азартные игры.
        /// </summary>
        public static string RootGambling {
            get {
                return ResourceManager.GetString("RootGambling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Здоровье.
        /// </summary>
        public static string RootHealthWellbeing {
            get {
                return ResourceManager.GetString("RootHealthWellbeing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дом и Сад.
        /// </summary>
        public static string RootHomeGarden {
            get {
                return ResourceManager.GetString("RootHomeGarden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дети.
        /// </summary>
        public static string RootKids {
            get {
                return ResourceManager.GetString("RootKids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Досуг.
        /// </summary>
        public static string RootLeisure {
            get {
                return ResourceManager.GetString("RootLeisure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Медиа и Маркетинг.
        /// </summary>
        public static string RootMediaMarketing {
            get {
                return ResourceManager.GetString("RootMediaMarketing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Деньги.
        /// </summary>
        public static string RootMoney {
            get {
                return ResourceManager.GetString("RootMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Другое.
        /// </summary>
        public static string RootOther {
            get {
                return ResourceManager.GetString("RootOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Телефония и Интернет.
        /// </summary>
        public static string RootPhoneInternet {
            get {
                return ResourceManager.GetString("RootPhoneInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Общественные сервисы.
        /// </summary>
        public static string RootPublicServices {
            get {
                return ResourceManager.GetString("RootPublicServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Спорт.
        /// </summary>
        public static string RootSport {
            get {
                return ResourceManager.GetString("RootSport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Табачные изделия.
        /// </summary>
        public static string RootTobaccoProducts {
            get {
                return ResourceManager.GetString("RootTobaccoProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перевозки.
        /// </summary>
        public static string RootTransportation {
            get {
                return ResourceManager.GetString("RootTransportation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отпуск и Путешествия.
        /// </summary>
        public static string RootTravelVacation {
            get {
                return ResourceManager.GetString("RootTravelVacation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Коммунальные услуги.
        /// </summary>
        public static string RootUtilities {
            get {
                return ResourceManager.GetString("RootUtilities", resourceCulture);
            }
        }
    }
}
