//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Client {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Client() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Localization.Client", typeof(Client).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Войти.
        /// </summary>
        public static string ButtonEnter {
            get {
                return ResourceManager.GetString("ButtonEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Войти.
        /// </summary>
        public static string ButtonLogin {
            get {
                return ResourceManager.GetString("ButtonLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Еще отзывы.
        /// </summary>
        public static string ButtonMoreReview {
            get {
                return ResourceManager.GetString("ButtonMoreReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поиск.
        /// </summary>
        public static string ButtonSearch {
            get {
                return ResourceManager.GetString("ButtonSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация.
        /// </summary>
        public static string ButtonSignUp {
            get {
                return ResourceManager.GetString("ButtonSignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to о.
        /// </summary>
        public static string LabelAbout {
            get {
                return ResourceManager.GetString("LabelAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Найти компанию.
        /// </summary>
        public static string LabelFindCompany {
            get {
                return ResourceManager.GetString("LabelFindCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to опубликовано.
        /// </summary>
        public static string LabelPublished {
            get {
                return ResourceManager.GetString("LabelPublished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рейтинг.
        /// </summary>
        public static string LabelRating {
            get {
                return ResourceManager.GetString("LabelRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to отзыв(ов).
        /// </summary>
        public static string LabelReviews {
            get {
                return ResourceManager.GetString("LabelReviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to О нас.
        /// </summary>
        public static string LinkAbout {
            get {
                return ResourceManager.GetString("LinkAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все категории.
        /// </summary>
        public static string LinkAllCategories {
            get {
                return ResourceManager.GetString("LinkAllCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Блог.
        /// </summary>
        public static string LinkBlog {
            get {
                return ResourceManager.GetString("LinkBlog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Категории.
        /// </summary>
        public static string LinkCategories {
            get {
                return ResourceManager.GetString("LinkCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Контакты.
        /// </summary>
        public static string LinkContacts {
            get {
                return ResourceManager.GetString("LinkContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вопросы.
        /// </summary>
        public static string LinkFAQ {
            get {
                return ResourceManager.GetString("LinkFAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для компаний.
        /// </summary>
        public static string LinkForCompanies {
            get {
                return ResourceManager.GetString("LinkForCompanies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Политика Безопасности.
        /// </summary>
        public static string LinkPrivacy {
            get {
                return ResourceManager.GetString("LinkPrivacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сроки и Условия.
        /// </summary>
        public static string LinkTerms {
            get {
                return ResourceManager.GetString("LinkTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лучшие компании из основных категорий.
        /// </summary>
        public static string TitleBestCompaniesInMain {
            get {
                return ResourceManager.GetString("TitleBestCompaniesInMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прямая связь.
        /// </summary>
        public static string TitleContactUs {
            get {
                return ResourceManager.GetString("TitleContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Напишите нам.
        /// </summary>
        public static string TitleEmailUs {
            get {
                return ResourceManager.GetString("TitleEmailUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Присоеденяйтесь. Подключайтесь к нам через социальные сети.
        /// </summary>
        public static string TitleJoinSocial {
            get {
                return ResourceManager.GetString("TitleJoinSocial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Последние отзывы.
        /// </summary>
        public static string TitleLatestReviews {
            get {
                return ResourceManager.GetString("TitleLatestReviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сегодня самый обсуждаемый отзыв для о.
        /// </summary>
        public static string TitleReviewOfDay {
            get {
                return ResourceManager.GetString("TitleReviewOfDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поддержка.
        /// </summary>
        public static string TitleSupport {
            get {
                return ResourceManager.GetString("TitleSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лучших сайтов в категории.
        /// </summary>
        public static string TitleTopBestInCategory {
            get {
                return ResourceManager.GetString("TitleTopBestInCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Худших сайтов в категории.
        /// </summary>
        public static string TitleWorseInCategory {
            get {
                return ResourceManager.GetString("TitleWorseInCategory", resourceCulture);
            }
        }
    }
}
