//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Company {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Company() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Localization.Company", typeof(Company).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заголовок сообщения:.
        /// </summary>
        public static string BoxHeadline {
            get {
                return ResourceManager.GetString("BoxHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Детали сообщения:.
        /// </summary>
        public static string BoxMessageDetails {
            get {
                return ResourceManager.GetString("BoxMessageDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изображение бокса.
        /// </summary>
        public static string BoxPicture {
            get {
                return ResourceManager.GetString("BoxPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста, добавьте заглавие:.
        /// </summary>
        public static string BoxTitle {
            get {
                return ResourceManager.GetString("BoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить категорию.
        /// </summary>
        public static string ButtonAddCategory {
            get {
                return ResourceManager.GetString("ButtonAddCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить данную категорию.
        /// </summary>
        public static string ButtonRemoveCategory {
            get {
                return ResourceManager.GetString("ButtonRemoveCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить изображение.
        /// </summary>
        public static string ButtonRemoveImage {
            get {
                return ResourceManager.GetString("ButtonRemoveImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить изменения.
        /// </summary>
        public static string ButtonSaveChanges {
            get {
                return ResourceManager.GetString("ButtonSaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить настройки.
        /// </summary>
        public static string ButtonSaveSettings {
            get {
                return ResourceManager.GetString("ButtonSaveSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обновить.
        /// </summary>
        public static string ButtonUpdate {
            get {
                return ResourceManager.GetString("ButtonUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название категории.
        /// </summary>
        public static string CategoryName {
            get {
                return ResourceManager.GetString("CategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Категории.
        /// </summary>
        public static string CategoryTitle {
            get {
                return ResourceManager.GetString("CategoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название компании:.
        /// </summary>
        public static string CICompanyName {
            get {
                return ResourceManager.GetString("CICompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Страна:.
        /// </summary>
        public static string CICountry {
            get {
                return ResourceManager.GetString("CICountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описание:.
        /// </summary>
        public static string CIDescription {
            get {
                return ResourceManager.GetString("CIDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показать краткое имя:.
        /// </summary>
        public static string CIDisplayName {
            get {
                return ResourceManager.GetString("CIDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Покажите screenshot вашей главной страницы.
        /// </summary>
        public static string CIDisplayScreenshot {
            get {
                return ResourceManager.GetString("CIDisplayScreenshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email:.
        /// </summary>
        public static string CIEmail {
            get {
                return ResourceManager.GetString("CIEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Телефон:.
        /// </summary>
        public static string CIPhone {
            get {
                return ResourceManager.GetString("CIPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Город и адрес улицы:.
        /// </summary>
        public static string CIStreetAddress {
            get {
                return ResourceManager.GetString("CIStreetAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста, заполните информацию об Вашей компании..
        /// </summary>
        public static string CISubTitle {
            get {
                return ResourceManager.GetString("CISubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Информация о компании.
        /// </summary>
        public static string CITitle {
            get {
                return ResourceManager.GetString("CITitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to О Компании.
        /// </summary>
        public static string CITitleAbout {
            get {
                return ResourceManager.GetString("CITitleAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Контактная информация.
        /// </summary>
        public static string CITitleContactInfo {
            get {
                return ResourceManager.GetString("CITitleContactInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки для Вашего your-shop.ru.
        /// </summary>
        public static string CITitleSettings {
            get {
                return ResourceManager.GetString("CITitleSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузите изображение для Вашей компании.
        /// </summary>
        public static string CITitleUpload {
            get {
                return ResourceManager.GetString("CITitleUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Или загрузите логотип компании.
        /// </summary>
        public static string CIUploadCompanyImage {
            get {
                return ResourceManager.GetString("CIUploadCompanyImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website компании:.
        /// </summary>
        public static string CIWebsite {
            get {
                return ResourceManager.GetString("CIWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Почтовый Zip код:.
        /// </summary>
        public static string CIZip {
            get {
                return ResourceManager.GetString("CIZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Категории.
        /// </summary>
        public static string DashboardMenuCategories {
            get {
                return ResourceManager.GetString("DashboardMenuCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Инфо компании.
        /// </summary>
        public static string DashboardMenuCompany {
            get {
                return ResourceManager.GetString("DashboardMenuCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook Box.
        /// </summary>
        public static string DashboardMenuFacebook {
            get {
                return ResourceManager.GetString("DashboardMenuFacebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Гарантии-бокс.
        /// </summary>
        public static string DashboardMenuGuarantee {
            get {
                return ResourceManager.GetString("DashboardMenuGuarantee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Промо-бокс.
        /// </summary>
        public static string DashboardMenuPromo {
            get {
                return ResourceManager.GetString("DashboardMenuPromo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки отзывов.
        /// </summary>
        public static string DashboardMenuReview {
            get {
                return ResourceManager.GetString("DashboardMenuReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите URL-адрес Вашей Facebook страницы..
        /// </summary>
        public static string FBLabel {
            get {
                return ResourceManager.GetString("FBLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваши клиенты любят Вас? Докажите! Получите больше доверия со стороны клиентов, добавив Facebook Like бокс на страницу Вашего профиля..
        /// </summary>
        public static string FBMessage {
            get {
                return ResourceManager.GetString("FBMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Например, не надо платить за доставку, Вы получите свой товар в течении 5 дней с момента заказа online!.
        /// </summary>
        public static string GBDetails {
            get {
                return ResourceManager.GetString("GBDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Например, бесплатная доставка в течении 5 дней..
        /// </summary>
        public static string GBHeadline {
            get {
                return ResourceManager.GetString("GBHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бесплатная доставка? Беспроблемное возвращается? Если у вас есть услуги, которые вы можете гарантировать своим клиентам, вот место, чтобы продвигать его..
        /// </summary>
        public static string GBMessage {
            get {
                return ResourceManager.GetString("GBMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Например, быстрая и бесплатная перевозка!.
        /// </summary>
        public static string GBTitle {
            get {
                return ResourceManager.GetString("GBTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Действие.
        /// </summary>
        public static string LabelAction {
            get {
                return ResourceManager.GetString("LabelAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to или размер изображения будет изменен.
        /// </summary>
        public static string LabelImageResized {
            get {
                return ResourceManager.GetString("LabelImageResized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рекомендованный размер.
        /// </summary>
        public static string LabelRecommendedSize {
            get {
                return ResourceManager.GetString("LabelRecommendedSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки.
        /// </summary>
        public static string MenuAccountSettings {
            get {
                return ResourceManager.GetString("MenuAccountSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Профиль компании.
        /// </summary>
        public static string MenuCompanyProfile {
            get {
                return ResourceManager.GetString("MenuCompanyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Панель управления.
        /// </summary>
        public static string MenuDashboard {
            get {
                return ResourceManager.GetString("MenuDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Главная.
        /// </summary>
        public static string MenuHome {
            get {
                return ResourceManager.GetString("MenuHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приглашения.
        /// </summary>
        public static string MenuInvitations {
            get {
                return ResourceManager.GetString("MenuInvitations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Модули.
        /// </summary>
        public static string MenuModules {
            get {
                return ResourceManager.GetString("MenuModules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Профиль.
        /// </summary>
        public static string MenuMyProfile {
            get {
                return ResourceManager.GetString("MenuMyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цены.
        /// </summary>
        public static string MenuPricing {
            get {
                return ResourceManager.GetString("MenuPricing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Продукты.
        /// </summary>
        public static string MenuProduct {
            get {
                return ResourceManager.GetString("MenuProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ресурсы.
        /// </summary>
        public static string MenuResources {
            get {
                return ResourceManager.GetString("MenuResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отзывы.
        /// </summary>
        public static string MenuReviews {
            get {
                return ResourceManager.GetString("MenuReviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выйти.
        /// </summary>
        public static string MenuSignout {
            get {
                return ResourceManager.GetString("MenuSignout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статистика.
        /// </summary>
        public static string MenuStatistics {
            get {
                return ResourceManager.GetString("MenuStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователи.
        /// </summary>
        public static string MenuUserManage {
            get {
                return ResourceManager.GetString("MenuUserManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добро пожаловать.
        /// </summary>
        public static string MenuWelcome {
            get {
                return ResourceManager.GetString("MenuWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Почему мы.
        /// </summary>
        public static string MenuWhyUs {
            get {
                return ResourceManager.GetString("MenuWhyUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Например, наши обязательства перед клиентами!.
        /// </summary>
        public static string PromoBoxCommited {
            get {
                return ResourceManager.GetString("PromoBoxCommited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дайте клиентам узнать больше о Вашей компании. Используйте Promotion бокс, чтобы показать основные преимущества Вашего бренда. Например, обязательства по обслуживанию клиентов..
        /// </summary>
        public static string PromoBoxMessage {
            get {
                return ResourceManager.GetString("PromoBoxMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Например, название компании и слоган..
        /// </summary>
        public static string PromoBoxTagline {
            get {
                return ResourceManager.GetString("PromoBoxTagline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Например, мы относимся к нашим клиентам так, как хотели бы, чтобы относились к нам, - с уважением, поддержкой и добротой..
        /// </summary>
        public static string PromoBoxTreat {
            get {
                return ResourceManager.GetString("PromoBoxTreat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Необходимо ли запрашивать код для отзыва?.
        /// </summary>
        public static string RSCodeRequired {
            get {
                return ResourceManager.GetString("RSCodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Посмотреть мой профиль на TrustSystem.
        /// </summary>
        public static string ViewProfileTs {
            get {
                return ResourceManager.GetString("ViewProfileTs", resourceCulture);
            }
        }
    }
}
