//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrustSystems3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Afs
    {
        public Afs()
        {
            this.TemplateDelay = 7;
        }
    
        public int Id { get; set; }
        public string SenderName { get; set; }
        public InviteFrequencyType InviteFrequency { get; set; }
        public int TemplateDelay { get; set; }
        public string TemplateSubject { get; set; }
        public string TemplateBody { get; set; }
    
        public virtual Companies Companies { get; set; }
        public virtual Template Template { get; set; }
    }
}
