//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrustSystems3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Companies
    {
        public Companies()
        {
            this.IsOrderRequired = false;
            this.CompanyUsers = new HashSet<CompanyUsers>();
            this.Reviews = new HashSet<Review>();
            this.Categories = new HashSet<Category>();
            this.Invitation = new HashSet<Invitation>();
            this.CompanyBox = new HashSet<CompanyBox>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Slug { get; set; }
        public string Description { get; set; }
        public string Website { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<int> Country { get; set; }
        public int CityId { get; set; }
        public string Address { get; set; }
        public string Zip { get; set; }
        public string Logo { get; set; }
        public int CategoryId { get; set; }
        public bool IsOrderRequired { get; set; }
    
        public virtual ICollection<CompanyUsers> CompanyUsers { get; set; }
        public virtual ICollection<Review> Reviews { get; set; }
        public virtual ICollection<Category> Categories { get; set; }
        public virtual ICollection<Invitation> Invitation { get; set; }
        public virtual Afs Afs { get; set; }
        public virtual ICollection<CompanyBox> CompanyBox { get; set; }
    }
}
