//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrustSystems3
{
    using System;
    
    public enum CountryType : int
    {
        Russia = 7,
        Ukraine = 380,
        Belarus = 375,
        USA = 1
    }
}
