//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrustSystems3
{
    using System;
    
    public enum InivationStatusType : byte
    {
        Pending = 0,
        Sent = 1,
        Error = 2,
        Canceled = 3,
        Reviewed = 4
    }
}
