//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrustSystems3
{
    using System;
    
    public enum LogType : byte
    {
        Event = 0,
        Error = 1,
        Client = 2,
        Company = 3,
        SchedulerEmailJob = 4,
        SchedulerInviteJob = 5
    }
}
