//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrustSystems3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public Review()
        {
            this.Rating = 0;
            this.IsConfirmed = false;
            this.ReviewComment = new HashSet<ReviewComment>();
            this.ReviewUsefull = new HashSet<ReviewUsefull>();
            this.ReviewLike = new HashSet<ReviewLike>();
            this.ReviewWarning = new HashSet<ReviewWarning>();
        }
    
        public int Id { get; set; }
        public int CompanyId { get; set; }
        public string UserId { get; set; }
        public int Rating { get; set; }
        public string OrderId { get; set; }
        public string ReviewShort { get; set; }
        public string ReviewFull { get; set; }
        public bool IsConfirmed { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DatePublished { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
    
        public virtual ICollection<ReviewComment> ReviewComment { get; set; }
        public virtual ICollection<ReviewUsefull> ReviewUsefull { get; set; }
        public virtual Companies Companies { get; set; }
        public virtual ICollection<ReviewLike> ReviewLike { get; set; }
        public virtual ICollection<ReviewWarning> ReviewWarning { get; set; }
    }
}
