//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrustSystems3
{
    using System;
    using System.Collections.Generic;
    
    public partial class RootCategory
    {
        public RootCategory()
        {
            this.Category = new HashSet<Category>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Slug { get; set; }
        public string Icon { get; set; }
    
        public virtual ICollection<Category> Category { get; set; }
    }
}
