//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrustSystems3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Template
    {
        public Template()
        {
            this.Language = 7;
            this.Delay = 7;
            this.Afs = new HashSet<Afs>();
        }
    
        public int Id { get; set; }
        public int Language { get; set; }
        public int Delay { get; set; }
        public string Subject { get; set; }
        public string Body { get; set; }
    
        public virtual ICollection<Afs> Afs { get; set; }
    }
}
