//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrustSystems3
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TSModelContainer : DbContext
    {
        public TSModelContainer()
            : base("name=TSModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<Review> Reviews { get; set; }
        public virtual DbSet<ReviewComment> ReviewComments { get; set; }
        public virtual DbSet<RootCategory> RootCategories { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<ReviewUsefull> ReviewUsefulls { get; set; }
        public virtual DbSet<Cities> Cities { get; set; }
        public virtual DbSet<Companies> Companies { get; set; }
        public virtual DbSet<CompanyUsers> CompanyUsers { get; set; }
        public virtual DbSet<Contacts> Contacts { get; set; }
        public virtual DbSet<Invitation> Invitations { get; set; }
        public virtual DbSet<Template> Templates { get; set; }
        public virtual DbSet<Afs> AfsSettings { get; set; }
        public virtual DbSet<Logger> LoggerSet { get; set; }
        public virtual DbSet<ReviewLike> ReviewLikes { get; set; }
        public virtual DbSet<ReviewWarning> ReviewWarnings { get; set; }
        public virtual DbSet<CompanyBox> CompanyBoxes { get; set; }
    }
}
